name: PHP

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php-versions: ['8.0', '8.1', '7.4']
    name: Tests - PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extension: xdebug
        coverage: xdebug
    - name: Install dependencies
      working-directory: .
      run: composer install --no-interaction --prefer-dist --no-suggest
    - name: Lint composer.json
      working-directory: .
      run: composer validate
    - name: Run Tests
      working-directory: .
      run: composer test:ci
